login:
    path: /login
    defaults: { _controller: AdminBundle:Security:login }

logout:
    path: /logout
    defaults: { _controller: AdminBundle:Security:logout }

dashboard:
    path: /dashboard
    defaults: { _controller: AdminBundle:Dashboard:index }

profile:
    path: /profile
    defaults: { _controller: AdminBundle:Dashboard:profile }


#### Admin CRUD
admin_show:
    path: /admins/{id}
    defaults: { _controller: AdminBundle:Admin:show }
#### Admin CRUD