login:
    path: /login
    defaults: { _controller: AdminBundle:Security:login }

logout:
    path: /logout
    defaults: { _controller: AdminBundle:Security:logout }

dashboard:
    path: /dashboard
    defaults: { _controller: AdminBundle:Dashboard:index }