services:
#    admin.example:
#        class: AdminBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    admin.user_manager:
        class: AdminBundle\Manager\AdminManager
        arguments: ['@doctrine.orm.entity_manager', "AdminBundle\\Entity\\Admin", true]

    admin.user_provider:
        class: AdminBundle\Security\User\UserProvider
        arguments: ['@admin.user_manager']